models.py
from app import db
from datetime import datetime
import re
from flask_security import UserMixin, RoleMixin

def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', s)

post_tags = db.Table('post_tags',
                     db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
                     db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
                     )

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    url_for_pers = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.generate_urls()

    tags = db.relationship('Tag', secondary=post_tags, backref=db.backref('posts', lazy='dynamic'))

    def generate_urls(self):
        if self.title:
            self.url_for_pers = slugify(self.title)

    def __repr__(self):
        return '<Post id: {}, title: {}>'.format(self.id, self.title)

class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    url_for_tag = db.Column(db.String(100))

    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.url_for_tag = slugify(self.name)

    def __repr__(self):
        return '<{}>'.format(self.name)

# Flask_Security

role_users = db.Table('role_users',
                      db.Column('user_id', db.Integer(), db.ForeignKey('user.id')),
                      db.Column('role_id', db.Integer(), db.ForeignKey('role.id'))
                      )

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean)
    roles = db.relationship('Role', secondary=role_users, backref=db.backref('users', lazy='dynamic'))

class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), unique=True)
    descr = db.Column(db.String(255))

app.py
from flask import Flask, render_template
from config import Configuration
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView
from flask_security import SQLAlchemyUserDatastore, Security, current_user
from flask import request, redirect, url_for
from flask_admin import AdminIndexView



app = Flask(__name__)
app.config.from_object(Configuration)

db = SQLAlchemy(app)


migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)
from models import *

class AdminView(ModelView):
    def is_accessible(self):
        return current_user.has_role('admin')

    def inaccessible_callback(self, name, **kwargs):
        return redirect(url_for('security.login', next=request.url))

class HomeAdminView(AdminIndexView):
    def is_accessible(self):
        return current_user.has_role('admin')

    def inaccessible_callback(self, name, **kwargs):
        return redirect(url_for('security.login', next=request.url))


admin = Admin(app, 'FlaskApp', url='/', index_view=HomeAdminView(name='Home'))
admin.add_view(AdminView(Post, db.session))
admin.add_view(AdminView(Tag, db.session))
#Flas Sec

user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)

main.py
from app import app
import view
from posts.blueprint import posts
from app import db

app.register_blueprint(posts, url_prefix='/blog')

if __name__ == "__main__":
    app.run(debug=True)

posts/blueprint.py
from flask import Blueprint
from flask import render_template
from flask import request
from .froms import PostForm
from models import Post, Tag
from app import db
from flask import redirect, url_for
from flask_security import login_required


posts = Blueprint('posts', __name__, template_folder='templates')

@posts.route('/create', methods=['POST', 'GET'])
@login_required
def create_post():

    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']

        try:
            post = Post(title=title, body=body)
            db.session.add(post)
            db.session.commit()
        except:
            pass
        return redirect(url_for('posts.index'))

    form = PostForm()
    return render_template('posts/create_post.html', form=form)


@posts.route('/<url_for_pers>/edit', methods=['POST', 'GET'])
@login_required
def edit_post(url_for_pers):
    post = Post.query.filter(Post.url_for_pers==url_for_pers).first()

    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()

        return redirect(url_for('posts.post_detail', url_for_pers=post.url_for_pers))

    form = PostForm(obj=post)
    return render_template('posts/edit.html', post=post, form=form)


@posts.route('/')
def index():

    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page=1


    posts = Post.query.order_by(Post.created.desc())

    pages = posts.paginate(page=page, per_page=6)


    return render_template('posts/index.html', posts=posts, pages=pages)

@posts.route('/<url_for_pers>')
def post_detail(url_for_pers):
    post = Post.query.filter(Post.url_for_pers==url_for_pers).first()
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags)

@posts.route('/tag/<url_for_tag>')
def tag_detail(url_for_tag):
    tag = Tag.query.filter(Tag.url_for_tag==url_for_tag).first()
    posts = tag.posts.all()
    return render_template('posts/tag_detail.html', tag=tag, posts=posts)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css')}}">
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %}  | Flask App
    </title>
</head>
<body>
<nav class="site-header sticky-top py-1">
      <div class="container d-flex flex-column flex-md-row justify-content-between">
        <a class="py-2" href="#">
          <svg version="1.1" id="Logotype" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="24px" height="24px" viewBox="1131.429 2066.937 273.544 346.489" enable-background="new 1131.429 2066.937 273.544 346.489" xml:space="preserve">
<g transform="matrix(23.25581395348837, 0, 0, 23.25581395348837, 0, 0)">
	<g transform="matrix(1.471494403518133, 0, 0, 1.471494403518133, -38.017720703566944, -31.558732314540904)">
		<g transform="matrix(1.5052599999999998, 0, 0, 1.5052599999999998, 48.153710000000004, 25.363699999999998)">
			<g>
				<path id="rnd1" fill="#DD2C00" d="M12.449,41.595c0,1.486-1.169,2.655-2.655,2.655s-2.655-1.169-2.655-2.655      c0-1.486,2.386-2.726,2.117-4.071C9.794,37.524,12.449,39.443,12.449,41.595z"/>
				<path id="rnd2" fill="#FF5722" d="M11.387,42.303c0-1.345-1.593-2.655-1.593-2.655c0,1.076-1.593,1.579-1.593,2.655      c0,0.891,0.702,1.593,1.593,1.593C10.685,43.896,11.387,43.195,11.387,42.303z"/>
				<path id="rnd3" fill="#FFC107" d="M8.908,42.906c0-0.603,0.885-0.948,0.885-1.488c0,0,0.885,0.678,0.885,1.488      c0,0.447-0.396,0.81-0.885,0.81C9.304,43.716,8.908,43.353,8.908,42.906z"/>
			</g>
		</g>
	</g>
</g>
</svg>
        </a>
        <a class="py-2 d-none d-md-inline-block" href="{{ url_for('index') }}">Home</a>
        <a class="py-2 d-none d-md-inline-block" href="{{ url_for('posts.index') }}">Blog</a>
          <a class="py-2 d-none d-md-inline-block" href="{{ url_for('posts.create_post') }}">Create Post</a>
      </div>
    </nav>

    <div class="container">
        <div class="row">
            {% block content_title %}

            {% endblock %}
        </div>
        {% block content %}

        {% endblock %}
    </div>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
    Blog
{% endblock %}



{% block content_title %}
    <h1 class="display-4 col-md-6 offset-md-3" align="center">New Blog SorpDEv</h1>
{% endblock %}



{% block content %}
    Content
{% endblock %}

templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
    Create Post
{% endblock %}

{% block content_title %}
    <h1 class="display-4 col-md-6 offset-md-3" align="center">New Post</h1>
{% endblock %}

{% block content %}
<div class="col-lg-6">
    <form action="{{ url_for('posts.create_post') }}" method="post">
        {% for field in form %}
            <div class="form-group">
                {{ field.label(class="control-label") }}
                {{ field(class="form-control") }}
            </div>
        {% endfor %}
    <button class="btn btn-lg btn-success">Create post</button>
    </form>
</div>

{% endblock %}

templates/posts/edit.html
{% extends 'base.html' %}

{% block title %}
    Edit Post
{% endblock %}

{% block content_title %}
    <h1 class="display-4 col-md-6 offset-md-3" align="center">Edit Post</h1>
{% endblock %}

{% block content %}
<div class="col-lg-6">
    <form action="{{ url_for('posts.edit_post', url_for_pers=post.url_for_pers) }}" method="post">
        {% for field in form %}
            <div class="form-group">
                {{ field.label(class="control-label") }}
                {{ field(class="form-control") }}
            </div>
        {% endfor %}
    <button class="btn btn-lg btn-success">Edit post</button>
    </form>
</div>

{% endblock %}

templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
    Main Blog Page
{% endblock %}

{% block content_title %}
    <div class="col-md-6 offset-md-3" align="center">
        <h1>Posts</h1>
    </div>
{% endblock %}

{% block content %}

    {% for post in pages.items %}

        <p>
            <a href="{{ url_for('posts.post_detail', url_for_pers=post.url_for_pers) }}">{{ post.title }}</a>
        </p>

    {% endfor %}

    <nav>
  <ul class="pagination">
    <li {% if not pages.has_prev %}class="disabled"{% endif %} class="page-item">
      <a class="page-link" href="./?page={{ pages.prev_num }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
  {% for page in pages.iter_pages() %}

      <li class="page-item">
          <a class="page-link" href="./?page={{ page }}">{{ page }}</a>
      </li>

  {% endfor %}
    <li class="page-item">
      <a class="page-link disable" href="./?page={{ pages.next_num }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
  </ul>
</nav>


{% endblock %}

templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}


{% block content_title %}
{% endblock %}


{% block content %}
    {% for tag in tags %}

            <a href="{{ url_for('posts.tag_detail', url_for_tag=tag.url_for_tag) }}">
            <span class="badge badge-pill badge-dark">{{ tag.name }}</span></a>

    {% endfor %}
    <div class="jumbotron jumbotron-fluid">
  <div class="container">
      <h1 class="display-4" align="center">{{ post.title }}</h1>
    <p class="lead">{{ post.body }}</p>
  </div>
    <a href="{{ url_for('posts.edit_post', url_for_pers=post.url_for_pers) }}"><button class="btn btn-lg btn-success col-md-3 offset-md-8">Edit Post</button></a>
</div>
{% endblock %}

templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ tag.name }} Posts
{% endblock %}

{% block content_title %}
    Posts for: "{{ tag.name }}"
{% endblock %}


{% block content %}
    {% for post in posts %}
        <p>
            <a href="{{ url_for('posts.post_detail', url_for_pers=post.url_for_pers) }}">{{ post.title }}</a>
        </p>
    {% endfor %}
{% endblock %}

templates/security/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}
    <div class="flashes">
    {% for category, message in messages %}
      <div class="alert alert-warning {{ category }}">{{ message }}</div>
    {% endfor %}
    </div>
  {% endif %}
{%- endwith %}

templates/security/login_user.html
{% extends 'base.html' %}

{% block title %}
    Login
{% endblock %}

{% block content_title %}
    <h1 class="display-4 col-md-6 offset-md-3" align="center">{{ _('Login') }}</h1>
{% endblock %}

{% block content %}
    <div class="col-md-6 offset-3">
{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}
<form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
  {{ login_user_form.hidden_tag() }}
  {{ render_field_with_errors(login_user_form.email, class="form-control") }}
  {{ render_field_with_errors(login_user_form.password, class="form-control") }}
  {{ render_field_with_errors(login_user_form.remember) }}
  {{ render_field(login_user_form.next) }}
  {{ render_field(login_user_form.submit, class="btn btn-lg btn-success") }}
</form>
{% include "security/_menu.html" %}
</div>
{% endblock %}